# Production Data Cleaning and Historical Dataset

## Crop Yield Risk & Advisory Dashboard

### This notebook loads district-level Area, Production and Yield data for multiple years from the Government of India UPAg portal, standardizes the datasets, filters the project scope, and creates a historical production dataset.

In [1]:
import pandas as pd

In [2]:
# Loading the datset from 2021 to 2025
df_2021 = pd.read_csv(
    "../../data/raw/DES-District-Data-For-2021-22.csv"
)

df_2022 = pd.read_csv(
    "../../data/raw/DES-District-Data-For-2022-23.csv"
)

df_2023 = pd.read_csv(
    "../../data/raw/DES-District-Data-For-2023-24.csv"
)

df_2024 = pd.read_csv(
    "../../data/raw/DES-District-Data-For-2024-25.csv"
)

## Checking if all dataframe contain same columns or not

In [3]:
df_2021.columns.tolist()

['State',
 'District',
 'Crop',
 'Season',
 'Area-2021-22',
 'Production-2021-22',
 'Yield-2021-22']

In [4]:
df_2022.columns.tolist()

['State',
 'District',
 'Crop',
 'Season',
 'Area-2022-23',
 'Production-2022-23',
 'Yield-2022-23']

In [5]:
df_2023.columns.tolist()

['State',
 'District',
 'Crop',
 'Season',
 'Area-2023-24',
 'Production-2023-24',
 'Yield-2023-24']

In [6]:
df_2024.columns.tolist()

['State',
 'District',
 'Crop',
 'Season',
 'Area-2024-25',
 'Production-2024-25',
 'Yield-2024-25']

In [7]:
# Comparing the shape of dataframes from 2021 to 2024

print("2021-22:", df_2021.shape)
print("2022-23:", df_2022.shape)
print("2023-24:", df_2023.shape)
print("2024-25:", df_2024.shape)

2021-22: (24025, 7)
2022-23: (25183, 7)
2023-24: (25556, 7)
2024-25: (23282, 7)

In [8]:
target_states = [
    "Uttar Pradesh",
    "Punjab",
    "Haryana"
]

In [9]:
# Checking for target state in every year 

for year , dataset in [ ("2021-22", df_2021),
    ("2022-23", df_2022),
    ("2023-24", df_2023),
    ("2024-25", df_2024)
]:
    print("\nYEAR:", year)

    for state in target_states:
        print(state , (dataset["State"]==state).sum())

YEAR: 2021-22
Uttar Pradesh 3031
Punjab 452
Haryana 690

YEAR: 2022-23
Uttar Pradesh 3127
Punjab 520
Haryana 551

YEAR: 2023-24
Uttar Pradesh 3094
Punjab 515
Haryana 526

YEAR: 2024-25
Uttar Pradesh 3171
Punjab 537
Haryana 554

In [10]:
# Checking for target crop in every year

target_crops = [
    "Wheat",
    "Rice",
    "Maize"
]

In [11]:
for year , dataset in [ ("2021-22", df_2021),
    ("2022-23", df_2022),
    ("2023-24", df_2023),
    ("2024-25", df_2024)
]:
    print("\nYEAR:", year)

    for crop in target_crops:
        print(crop , (dataset["Crop"]==crop).sum())

YEAR: 2021-22
Wheat 1103
Rice 1754
Maize 1777

YEAR: 2022-23
Wheat 1111
Rice 1874
Maize 1861

YEAR: 2023-24
Wheat 1078
Rice 1837
Maize 2017

YEAR: 2024-25
Wheat 966
Rice 1661
Maize 1885

In [12]:
# Creating a function to processed the data of every year 

def clean_production_data(df , year):

    filtered_df = df[
        df["State"].isin(target_states)&
        df["Crop"].isin(target_crops)&
        (df["Season"]=="Total")
        ].copy()

    area_column = f"Area-{year}"
    production_column = f"Production-{year}"
    yield_column = f"Yield-{year}"

    filtered_df = filtered_df.rename(
        columns={
            area_column : "Area",
            production_column : "Production",
            yield_column : "Yield"}
    )

    filtered_df["Year"] = year

    filtered_df = filtered_df[
        [
            "State",
            "District",
            "Crop",
            "Year",
            "Area",
            "Production",
            "Yield"
        ]
    ]

    return filtered_df

In [13]:
# Calling the function 

clean_2021 = clean_production_data(
    df_2021,
    "2021-22"
)

clean_2022 = clean_production_data(
    df_2022,
    "2022-23"
)

clean_2023 = clean_production_data(
    df_2023,
    "2023-24"
)

clean_2024 = clean_production_data(
    df_2024,
    "2024-25"
)

In [14]:
clean_2021.head()

        State District   Crop     Year  Area  Production   Yield
5969  Haryana   Ambala   Rice  2021-22  0.94        3.86  4107.0
5971  Haryana   Ambala  Wheat  2021-22  0.88        3.61  4107.0
5973  Haryana   Ambala  Maize  2021-22  0.00        0.01  3945.0
6003  Haryana  Bhiwani   Rice  2021-22  0.22        0.47  2099.0
6005  Haryana  Bhiwani  Wheat  2021-22  0.87        3.71  4271.0

In [15]:
clean_2022.head()

        State District   Crop     Year  Area  Production   Yield
6759  Haryana   Ambala   Rice  2022-23  1.05        3.90  3719.0
6761  Haryana   Ambala  Wheat  2022-23  0.89        4.12  4639.0
6763  Haryana   Ambala  Maize  2022-23  0.00        0.00  3455.0
6780  Haryana  Bhiwani   Rice  2022-23  0.26        0.73  2781.0
6782  Haryana  Bhiwani  Wheat  2022-23  0.91        3.71  4098.0

In [16]:
# Concatinating the production_data

production_history = pd.concat(
    [
        clean_2021,
        clean_2022,
        clean_2023,
        clean_2024
    ],
    ignore_index = True )

### Inspecting the historical data

In [17]:
production_history.head()

     State District   Crop     Year  Area  Production   Yield
0  Haryana   Ambala   Rice  2021-22  0.94        3.86  4107.0
1  Haryana   Ambala  Wheat  2021-22  0.88        3.61  4107.0
2  Haryana   Ambala  Maize  2021-22  0.00        0.01  3945.0
3  Haryana  Bhiwani   Rice  2021-22  0.22        0.47  2099.0
4  Haryana  Bhiwani  Wheat  2021-22  0.87        3.71  4271.0

In [18]:
production_history.tail()

              State  District   Crop     Year  Area  Production   Yield
1398  Uttar Pradesh     Unnao  Wheat  2024-25  2.23        6.89  3094.0
1399  Uttar Pradesh     Unnao  Maize  2024-25  0.23        0.65  2816.0
1400  Uttar Pradesh  Varanasi   Rice  2024-25  0.77        2.35  3069.0
1401  Uttar Pradesh  Varanasi  Wheat  2024-25  0.63        2.23  3561.0
1402  Uttar Pradesh  Varanasi  Maize  2024-25  0.02        0.05  2662.0

In [19]:
production_history.shape

(1403, 7)

In [20]:
production_history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1403 entries, 0 to 1402
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   State       1403 non-null   object
 1   District    1403 non-null   object
 2   Crop        1403 non-null   object
 3   Year        1403 non-null   object
 4   Area        1403 non-null   float64
 5   Production  1403 non-null   float64
 6   Yield       1403 non-null   float64
dtypes: float64(3), object(4)
memory usage: 76.9+ KB

In [21]:
production_history.describe()

              Area   Production        Yield
count  1403.000000  1403.000000  1403.000000
mean      0.795346     2.979266  3349.583749
std       0.735683     3.095805   982.008703
min       0.000000     0.000000     0.000000
25%       0.070000     0.160000  2672.500000
50%       0.660000     2.230000  3338.000000
75%       1.370000     4.760000  4071.500000
max       3.290000    14.090000  6000.000000

In [22]:
# Verifying the years 

production_history["Year"].value_counts()

Year
2024-25    355
2021-22    353
2022-23    348
2023-24    347
Name: count, dtype: int64

In [23]:
production_history.isnull().sum()

State         0
District      0
Crop          0
Year          0
Area          0
Production    0
Yield         0
dtype: int64

In [24]:
production_history.duplicated(
    subset=[
        "State",
        "District",
        "Crop",
        "Year"
    ]
).sum()

np.int64(0)

In [25]:
# Checking the unqiue district in each state 

production_history.groupby("State")["District"].nunique()

State
Haryana          22
Punjab           23
Uttar Pradesh    75
Name: District, dtype: int64

In [26]:
pd.crosstab(
    production_history["Year"],
    production_history["Crop"]
)

Crop     Maize  Rice  Wheat
Year
2021-22    114   119    120
2022-23    109   119    120
2023-24    107   120    120
2024-25    115   120    120

In [27]:
# Sorting chronologically

production_history = production_history.sort_values(
    by=[
        "State",
        "District",
        "Crop",
        "Year"
    ]
).reset_index(drop=True)

In [28]:
production_history

              State  District   Crop     Year  Area  Production   Yield
0           Haryana    Ambala  Maize  2021-22  0.00        0.01  3945.0
1           Haryana    Ambala  Maize  2022-23  0.00        0.00  3455.0
2           Haryana    Ambala  Maize  2023-24  0.00        0.01  4642.0
3           Haryana    Ambala  Maize  2024-25  0.00        0.00  3714.0
4           Haryana    Ambala   Rice  2021-22  0.94        3.86  4107.0
...             ...       ...    ...      ...   ...         ...     ...
1398  Uttar Pradesh  Varanasi   Rice  2024-25  0.77        2.35  3069.0
1399  Uttar Pradesh  Varanasi  Wheat  2021-22  0.72        2.59  3595.0
1400  Uttar Pradesh  Varanasi  Wheat  2022-23  0.71        1.74  2454.0
1401  Uttar Pradesh  Varanasi  Wheat  2023-24  0.62        1.77  2836.0
1402  Uttar Pradesh  Varanasi  Wheat  2024-25  0.63        2.23  3561.0

[1403 rows x 7 columns]

In [29]:
# Checking for any whitespaces in text values

text_columns = ["State" , "District" , "Crop"]

for column in text_columns:
    production_history[column]=(
        production_history[column].astype("string").str.strip().str.replace(r"\s+"," " , regex = True))

In [32]:
# Adding an ordinary variable for year 

year_order = {
    "2021-22": 2021,
    "2022-23": 2022,
    "2023-24": 2023,
    "2024-25": 2024
}

production_history["Year_Order"] = (
    production_history["Year"].map(year_order)
)

In [33]:

production_history[
  ["Year" , "Year_Order"]].drop_duplicates().sort_values("Year_Order")

      Year  Year_Order
0  2021-22        2021
1  2022-23        2022
2  2023-24        2023
3  2024-25        2024

In [37]:
# Sorting the historical data 

production_history = production_history.sort_values(
    by = ["State" , "District" , "Crop" , "Year_Order"]).reset_index(drop=True)

In [38]:
# Chekcing if district have all same years or not 

history_coverage = (
    production_history.groupby(["State" , "District" , "Crop"])["Year"].nunique().reset_index(name = "Years_ Available"))

In [39]:
history_coverage.head()

     State District   Crop  Years_ Available
0  Haryana   Ambala  Maize                 4
1  Haryana   Ambala   Rice                 4
2  Haryana   Ambala  Wheat                 4
3  Haryana  Bhiwani  Maize                 3
4  Haryana  Bhiwani   Rice                 4

In [43]:
history_coverage["Years_ Available"].value_counts().sort_index()

Years_ Available
1      4
2      8
3      9
4    339
Name: count, dtype: int64

In [45]:
# Creating the missing years district/Crops flag

history_coverage["Complete_4_year_history"]=(history_coverage["Years_ Available"]==4)

In [46]:
history_coverage["Complete_4_year_history"].value_counts()

Complete_4_year_history
True     339
False     21
Name: count, dtype: int64

In [48]:
# Attaching this information to the main dataset

production_history = production_history.merge(
    history_coverage ,
    on = ["State" , "District" , "Crop"],
    how = "left"
    )

In [49]:
production_history.head()

,State,District,Crop,Year,Area,Production,Yield,Year_Order,Years_ Available,Complete_4_year_history
0,Haryana,Ambala,Maize,2021-22,0.00,0.01,3945.0,2021,4,True
1,Haryana,Ambala,Maize,2022-23,0.00,0.00,3455.0,2022,4,True
2,Haryana,Ambala,Maize,2023-24,0.00,0.01,4642.0,2023,4,True
3,Haryana,Ambala,Maize,2024-25,0.00,0.00,3714.0,2024,4,True
4,Haryana,Ambala,Rice,2021-22,0.94,3.86,4107.0,2021,4,True

In [57]:
# Inspecting one district 

example = production_history[
    (production_history["State"] == "Uttar Pradesh")
    & (production_history["District"] == "Meerut")
    & (production_history["Crop"] == "Wheat")
]


example

,State,District,Crop,Year,Area,Production,Yield,Year_Order,Years_ Available,Complete_4_year_history
1159,Uttar Pradesh,Meerut,Wheat,2021-22,0.81,3.39,4180.0,2021,4,True
1160,Uttar Pradesh,Meerut,Wheat,2022-23,0.78,3.33,4282.0,2022,4,True
1161,Uttar Pradesh,Meerut,Wheat,2023-24,0.62,2.59,4210.0,2023,4,True
1162,Uttar Pradesh,Meerut,Wheat,2024-25,0.72,2.93,4049.0,2024,4,True

In [58]:
# Each record in dataset must know previous year_yield

group_columns =[
    "State","District" , "Crop"]

production_history["Previous_Yield"]=(
    production_history.groupby(group_columns)["Yield"].shift(1))

In [59]:
production_history.head()

,State,District,Crop,Year,Area,Production,Yield,Year_Order,Years_ Available,Complete_4_year_history,Previous_Yield
0,Haryana,Ambala,Maize,2021-22,0.00,0.01,3945.0,2021,4,True,NaN
1,Haryana,Ambala,Maize,2022-23,0.00,0.00,3455.0,2022,4,True,3945.0
2,Haryana,Ambala,Maize,2023-24,0.00,0.01,4642.0,2023,4,True,3455.0
3,Haryana,Ambala,Maize,2024-25,0.00,0.00,3714.0,2024,4,True,4642.0
4,Haryana,Ambala,Rice,2021-22,0.94,3.86,4107.0,2021,4,True,NaN

In [62]:
# Calculating yield change

previous_yield_safe = production_history["Previous_Yield"].replace(0 , pd.NA)

production_history["Previous_yield_percentage"]=(
    (
        production_history["Yield"]-production_history["Previous_Yield"])/ previous_yield_safe)*100

In [64]:
# Caluclate Area Percentage 

production_history["Previous_area"]=(
    production_history.groupby(group_columns)["Area"].shift(1))

In [67]:
previous_area_safe = (
    production_history["Previous_area"].replace(0 , pd.NA))

production_history["Previous_Area_Percentage"] = (
    (
        production_history["Area"]-production_history["Previous_area"])/previous_area_safe)*100

In [71]:
# Calculating production change percentage

production_history["Previous_Production"] = (
    production_history.groupby(group_columns)["Production"].shift(1))

previous_production_safe=(
    production_history["Previous_Production"].replace(0 , pd.NA))

production_history["Production_Change_Pct"] = (
    (
        production_history["Production"]
        - production_history["Previous_Production"]
    )
    / previous_production_safe
) * 100

In [73]:
# History Average Yiled 

production_history["History_avg_yield"]=(
    production_history.groupby(group_columns)["Yield"].transform(
        lambda x: x.shift(1).expanding().mean()
    )
)

In [77]:
# Calculating Yield deviation from historical average

historical_yield_safe = (
    production_history["History_avg_yield"].replace(0 , pd.NA))

production_history["Yield_Deviation_Pct"] = (
    (
        production_history["Yield"]
        - production_history["History_avg_yield"]
    )
    / historical_yield_safe
) * 100

In [80]:
# Inspecting one complete history 

example = production_history[
    (production_history["State"] == "Uttar Pradesh")
    & (production_history["District"] == "Meerut")
    & (production_history["Crop"] == "Wheat")
][
    [
        "Year",
        "Area",
        "Production",
        "Yield",
        "Previous_Yield",
        "Previous_yield_percentage",
        "Previous_Area_Percentage",
        "History_avg_yield",
        "Yield_Deviation_Pct"
    ]
]

example

,Year,Area,Production,Yield,Previous_Yield,Previous_yield_percentage,Previous_Area_Percentage,History_avg_yield,Yield_Deviation_Pct
1159,2021-22,0.81,3.39,4180.0,NaN,NaN,NaN,NaN,NaN
1160,2022-23,0.78,3.33,4282.0,4180.0,2.440191,-3.703704,4180.0,2.440191
1161,2023-24,0.62,2.59,4210.0,4282.0,-1.681457,-20.512821,4231.0,-0.496337
1162,2024-25,0.72,2.93,4049.0,4210.0,-3.824228,16.129032,4224.0,-4.142992

In [81]:
# Summary Statisctics

production_history[
    [
        "Area",
        "Production",
        "Yield",
        "Previous_yield_percentage",
        "Previous_Area_Percentage",
        "Production_Change_Pct",
        "Yield_Deviation_Pct"
    ]
].describe()

              Area   Production        Yield
count  1403.000000  1403.000000  1403.000000
mean      0.795346     2.979266  3349.583749
std       0.735683     3.095805   982.008703
min       0.000000     0.000000     0.000000
25%       0.070000     0.160000  2672.500000
50%       0.660000     2.230000  3338.000000
75%       1.370000     4.760000  4071.500000
max       3.290000    14.090000  6000.000000

In [82]:
# Checking infinite values 

import numpy as np

np.isinf(production_history.select_dtypes(include="number")).sum()

Area                   0
Production             0
Yield                  0
Year_Order             0
Years_ Available       0
Previous_Yield         0
Previous_area          0
Previous_Production    0
History_avg_yield      0
dtype: int64

In [83]:
production_history.shape

(1403, 18)

In [84]:
production_history.isnull().sum()

State                          0
District                       0
Crop                           0
Year                           0
Area                           0
Production                     0
Yield                          0
Year_Order                     0
Years_ Available               0
Complete_4_year_history        0
Previous_Yield               360
Previous_yield_percentage    361
Previous_area                360
Previous_Area_Percentage     487
Previous_Production          360
Production_Change_Pct        448
History_avg_yield            360
Yield_Deviation_Pct          361
dtype: int64

In [86]:
# Saving the processed dataset

output_path = (
    "../../data/processed/"
    "production_history_2021_2025.csv"
)

production_history.to_csv(
    output_path,
    index=False
)

In [87]:
# Veirfying that file can be read back 

test_file = pd.read_csv(output_path)

In [88]:
test_file.head()

,State,District,Crop,Year,Area,Production,Yield,Year_Order,Years_ Available,Complete_4_year_history,Previous_Yield,Previous_yield_percentage,Previous_area,Previous_Area_Percentage,Previous_Production,Production_Change_Pct,History_avg_yield,Yield_Deviation_Pct
0,Haryana,Ambala,Maize,2021-22,0.00,0.01,3945.0,2021,4,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Haryana,Ambala,Maize,2022-23,0.00,0.00,3455.0,2022,4,True,3945.0,-12.420786,0.0,NaN,0.01,-100.0,3945.0,-12.420786
2,Haryana,Ambala,Maize,2023-24,0.00,0.01,4642.0,2023,4,True,3455.0,34.356006,0.0,NaN,0.00,NaN,3700.0,25.459459
3,Haryana,Ambala,Maize,2024-25,0.00,0.00,3714.0,2024,4,True,4642.0,-19.991383,0.0,NaN,0.01,-100.0,4014.0,-7.473842
4,Haryana,Ambala,Rice,2021-22,0.94,3.86,4107.0,2021,4,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [89]:
test_file.shape

(1403, 18)

In [90]:
production_history.shape

(1403, 18)