# Crop Production Data Exploration

### This notebook collects crop production data from the Government of India API and performs initial data profiling.

In [1]:
# Importing the libraries
import pandas as pd

In [2]:
# Load the csv file

file_path = "../../data/raw/DES-District-Data-For-2024-25.csv"
df = pd.read_csv(file_path)

In [3]:
df.head()

,State,District,Crop,Season,Area-2024-25,Production-2024-25,Yield-2024-25
0,Andaman And Nicobar Islands,Nicobars,Rice,Kharif,0.0,0.0,735.0
1,Andaman And Nicobar Islands,Nicobars,Rice,Total,0.0,0.0,735.0
2,Andaman And Nicobar Islands,Nicobars,Cereals,Kharif,0.0,0.0,735.0
3,Andaman And Nicobar Islands,Nicobars,Cereals,Total,0.0,0.0,735.0
4,Andaman And Nicobar Islands,Nicobars,Total Food Grains,Kharif,0.0,0.0,735.0

In [4]:
# Checking the rows and columns in data

df.shape

(23282, 7)

In [5]:
# List of columns
df.columns.tolist()

['State',
 'District',
 'Crop',
 'Season',
 'Area-2024-25',
 'Production-2024-25',
 'Yield-2024-25']

In [6]:
# Information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23282 entries, 0 to 23281
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               23282 non-null  str
 1   District            23282 non-null  str
 2   Crop                23282 non-null  str
 3   Season              23282 non-null  str
 4   Area-2024-25        23282 non-null  float64
 5   Production-2024-25  23254 non-null  float64
 6   Yield-2024-25       23254 non-null  float64
dtypes: float64(3), str(4)
memory usage: 1.2 MB

In [7]:
# Checking for null values

df.isnull().sum()

State                  0
District               0
Crop                   0
Season                 0
Area-2024-25           0
Production-2024-25    28
Yield-2024-25         28
dtype: int64

In [8]:
#Checking for duplicated values

df.duplicated().sum()

np.int64(0)

In [9]:
sorted(df["State"].unique())

['Andaman And Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu And Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Ladakh',
 'Madhya Pradesh',
 'Maharashtra',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand']

In [10]:
# Checking the count of target states

target_states = ["Uttar Pradesh" , "Punjab" , "Haryana"]

for state in target_states:
    print(state , (df["State"]==state).sum())

Uttar Pradesh 3171
Punjab 537
Haryana 554

In [11]:
sorted(df["Crop"].unique())

['Bajra',
 'Barley',
 'Cereals',
 'Gram',
 'Jowar',
 'Lentil',
 'Maize',
 'Moong',
 'Nutri/Coarse Cereals',
 'Other Pulses',
 'Ragi',
 'Rice',
 'Shree Anna /Nutri Cereals',
 'Small Millets',
 'Total Food Grains',
 'Total Pulses',
 'Tur',
 'Urad',
 'Wheat']

In [12]:
# Checkung for target crops

target_crops = ["Wheat", "Rice", "Maize"]

for crop in target_crops:
    print(crop, (df["Crop"] == crop).sum())

Wheat 966
Rice 1661
Maize 1885

In [13]:
df["Season"].unique()

<StringArray>
['Kharif', 'Total', 'Rabi', 'Summer']
Length: 4, dtype: str

### Missing rows

In [14]:
# Checking for rows where production or yield is nan/ null

missing_rows = df[
    df["Production-2024-25"].isnull() |
    df["Yield-2024-25"].isnull()]

missing_rows

,State,District,Crop,Season,Area-2024-25,Production-2024-25,Yield-2024-25
1303,Arunachal Pradesh,Longding,Lentil,Rabi,0.00,NaN,NaN
1304,Arunachal Pradesh,Longding,Lentil,Total,0.00,NaN,NaN
3763,Bihar,Madhepura,Bajra,Kharif,0.00,NaN,NaN
3764,Bihar,Madhepura,Bajra,Total,0.00,NaN,NaN
4189,Bihar,Rohtas,Other Pulses,Kharif,0.00,NaN,NaN
4343,Bihar,Sheikhpura,Ragi,Kharif,0.00,NaN,NaN
4344,Bihar,Sheikhpura,Ragi,Total,0.00,NaN,NaN
6543,Himachal Pradesh,Kullu,Gram,Rabi,0.00,NaN,NaN
6544,Himachal Pradesh,Kullu,Gram,Total,0.00,NaN,NaN
7510,Jharkhand,Jamtara,Bajra,Kharif,0.00,NaN,NaN
7511,Jharkhand,Jamtara,Bajra,Total,0.00,NaN,NaN
10306,Madhya Pradesh,Dhar,Lentil,Rabi,0.00,NaN,NaN
10307,Madhya Pradesh,Dhar,Lentil,Total,0.00,NaN,NaN
15893,Rajasthan,Deeg,Tur,Kharif,0.00,NaN,NaN
15894,Rajasthan,Deeg,Tur,Total,0.00,NaN,NaN
16114,Rajasthan,Jaipur,Lentil,Rabi,0.00,NaN,NaN
16115,Rajasthan,Jaipur,Lentil,Total,0.00,NaN,NaN
16264,Rajasthan,Jodhpur,Barley,Rabi,0.00,NaN,NaN
16265,Rajasthan,Jodhpur,Barley,Total,0.00,NaN,NaN
16275,Rajasthan,Jodhpur,Nutri/Coarse Cereals,Rabi,0.00,NaN,NaN
16298,Rajasthan,Karauli,Maize,Rabi,0.00,NaN,NaN
16299,Rajasthan,Karauli,Maize,Total,0.00,NaN,NaN
16479,Rajasthan,Pali,Tur,Kharif,0.00,NaN,NaN
16480,Rajasthan,Pali,Tur,Total,0.00,NaN,NaN
22767,Uttar Pradesh,Unnao,Jowar,Kharif,0.04,NaN,NaN
22768,Uttar Pradesh,Unnao,Jowar,Total,0.04,NaN,NaN
22810,Uttar Pradesh,Varanasi,Jowar,Kharif,0.05,NaN,NaN
22811,Uttar Pradesh,Varanasi,Jowar,Total,0.05,NaN,NaN

In [15]:
# Checking for which states production/yield is null

missing_rows["State"].value_counts()

State
Rajasthan            11
Bihar                 5
Uttar Pradesh         4
Arunachal Pradesh     2
Himachal Pradesh      2
Jharkhand             2
Madhya Pradesh        2
Name: count, dtype: int64

In [16]:
# Checking for which crops production/yield is null
missing_rows["Crop"].value_counts()

Crop
Lentil                  6
Bajra                   4
Tur                     4
Jowar                   4
Ragi                    2
Gram                    2
Barley                  2
Maize                   2
Other Pulses            1
Nutri/Coarse Cereals    1
Name: count, dtype: int64

In [17]:
# Checking for which season production/yield is null

missing_rows["Season"].value_counts()

Season
Total     13
Kharif     8
Rabi       7
Name: count, dtype: int64

In [18]:
df["Season"].value_counts()

Season
Total     9324
Kharif    6762
Rabi      4914
Summer    2282
Name: count, dtype: int64

In [19]:
example = df[
    (df["State"] == "Haryana") &
    (df["District"] == "Ambala") &
    (df["Crop"] == "Wheat")
]

example

,State,District,Crop,Season,Area-2024-25,Production-2024-25,Yield-2024-25
5850,Haryana,Ambala,Wheat,Rabi,0.89,4.13,4640.0
5851,Haryana,Ambala,Wheat,Total,0.89,4.13,4640.0

In [20]:
example = df[
    (df["State"] == "Uttar Pradesh") &
    (df["District"] == "Bareilly") &
    (df["Crop"] == "Maize")
]

example

,State,District,Crop,Season,Area-2024-25,Production-2024-25,Yield-2024-25
20269,Uttar Pradesh,Bareilly,Maize,Kharif,0.00,0.00,2606.0
20270,Uttar Pradesh,Bareilly,Maize,Rabi,0.00,0.00,2889.0
20271,Uttar Pradesh,Bareilly,Maize,Summer,0.08,0.27,3483.0
20272,Uttar Pradesh,Bareilly,Maize,Total,0.08,0.27,3474.0

In [21]:
seasonal_rows = example[example["Season"] != "Total"]

seasonal_rows["Area-2024-25"].sum()

np.float64(0.08)

In [22]:
seasonal_rows["Production-2024-25"].sum()

np.float64(0.27)

In [23]:
example[example["Season"] == "Total"]

,State,District,Crop,Season,Area-2024-25,Production-2024-25,Yield-2024-25
20272,Uttar Pradesh,Bareilly,Maize,Total,0.08,0.27,3474.0

In [25]:
target_total = df[
    df["Season"]== "Total"
    ]

target_total.shape

(9324, 7)

In [26]:
target_total.duplicated(
    subset = ["State" , "District" , "Crop"]
).sum()

np.int64(0)

In [27]:
# Processed subset

production_2024 = df[
    df["State"].isin(target_states)&df["Crop"].isin(target_crops)&(df["Season"]=="Total")].copy()

## Inspecting the production_2024

In [28]:
production_2024.head()

,State,District,Crop,Season,Area-2024-25,Production-2024-25,Yield-2024-25
5849,Haryana,Ambala,Rice,Total,0.84,3.55,4233.0
5851,Haryana,Ambala,Wheat,Total,0.89,4.13,4640.0
5853,Haryana,Ambala,Maize,Total,0.00,0.00,3714.0
5867,Haryana,Bhiwani,Rice,Total,0.32,1.23,3805.0
5869,Haryana,Bhiwani,Wheat,Total,1.00,4.76,4735.0

In [29]:
production_2024.tail()

,State,District,Crop,Season,Area-2024-25,Production-2024-25,Yield-2024-25
22760,Uttar Pradesh,Unnao,Wheat,Total,2.23,6.89,3094.0
22764,Uttar Pradesh,Unnao,Maize,Total,0.23,0.65,2816.0
22801,Uttar Pradesh,Varanasi,Rice,Total,0.77,2.35,3069.0
22803,Uttar Pradesh,Varanasi,Wheat,Total,0.63,2.23,3561.0
22807,Uttar Pradesh,Varanasi,Maize,Total,0.02,0.05,2662.0

In [30]:
production_2024.sample()

,State,District,Crop,Season,Area-2024-25,Production-2024-25,Yield-2024-25
22758,Uttar Pradesh,Unnao,Rice,Total,1.37,2.97,2173.0

In [31]:
production_2024.shape

(355, 7)

In [32]:
production_2024.isnull().sum()

State                 0
District              0
Crop                  0
Season                0
Area-2024-25          0
Production-2024-25    0
Yield-2024-25         0
dtype: int64

In [35]:
production_2024.duplicated(
    subset=["State", "District", "Crop"]
).sum()

np.int64(0)

In [36]:
# Renaming the column - Area , Production and Yield

production_2024 = production_2024.rename(
    columns={
        "Area-2024-25": "Area",
        "Production-2024-25": "Production",
        "Yield-2024-25": "Yield"
    }
)

In [37]:
# Adding the year 2024-2025

production_2024["Year"] = "2024-25"

In [39]:
production_2024.head()

        State District   Crop Season  Area  Production   Yield     Year
5849  Haryana   Ambala   Rice  Total  0.84        3.55  4233.0  2024-25
5851  Haryana   Ambala  Wheat  Total  0.89        4.13  4640.0  2024-25
5853  Haryana   Ambala  Maize  Total  0.00        0.00  3714.0  2024-25
5867  Haryana  Bhiwani   Rice  Total  0.32        1.23  3805.0  2024-25
5869  Haryana  Bhiwani  Wheat  Total  1.00        4.76  4735.0  2024-25

In [41]:
production_2024 = production_2024.drop(columns = ["Season"])

In [42]:
production_2024.head()

        State District   Crop  Area  Production   Yield     Year
5849  Haryana   Ambala   Rice  0.84        3.55  4233.0  2024-25
5851  Haryana   Ambala  Wheat  0.89        4.13  4640.0  2024-25
5853  Haryana   Ambala  Maize  0.00        0.00  3714.0  2024-25
5867  Haryana  Bhiwani   Rice  0.32        1.23  3805.0  2024-25
5869  Haryana  Bhiwani  Wheat  1.00        4.76  4735.0  2024-25

In [43]:
# Putting columns in a clean order 

production_2024 = production_2024[
    [
        "State",
        "District",
        "Crop",
        "Year",
        "Area",
        "Production",
        "Yield"
    ]
]

In [44]:
production_2024.head()

        State District   Crop     Year  Area  Production   Yield
5849  Haryana   Ambala   Rice  2024-25  0.84        3.55  4233.0
5851  Haryana   Ambala  Wheat  2024-25  0.89        4.13  4640.0
5853  Haryana   Ambala  Maize  2024-25  0.00        0.00  3714.0
5867  Haryana  Bhiwani   Rice  2024-25  0.32        1.23  3805.0
5869  Haryana  Bhiwani  Wheat  2024-25  1.00        4.76  4735.0